services:
  pg:
    image: postgres:latest
    container_name: pg
    restart: always
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=crud
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: